# Generated by Django 5.1 on 2024-08-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "question_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("question", models.TextField()),
                ("subquestion", models.TextField(null=True)),
                ("possible_answers", models.TextField(null=True)),
                ("multiple_answers", models.BooleanField(default=False)),
                ("answer_type", models.CharField(max_length=8)),
                ("description", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("components", "Components"),
                            ("water", "Water"),
                            ("crops", "Crops"),
                        ],
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "subquestion_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(null=True)),
                ("scenario_id", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
            ],
        ),
    ]
