# Generated by Django 5.1 on 2025-03-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="matrix_answers",
            field=models.BooleanField(default=False),
        ),
    ]
