# Generated by Django 5.1.5 on 2025-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyquestion_matrix_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='category',
            field=models.CharField(choices=[('components', 'Components'), ('crops', 'Crops'), ('water', 'Water')], max_length=60, null=True),
        ),
    ]
